log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "kumbio@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`testing.api.kumbio.com`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`testing.api.kumbio.com`)"
      entryPoints:
        - flower
      service: flower
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    kumbio-app-secure-router:
      rule: "Host(`testing.app.kumbio.com`)"
      entryPoints:
        - web-secure
      service: kumbio-app
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    kumbio-booking-secure-router:
      rule: "Host(`testing.agenda.kumbio.com`)"
      entryPoints:
        - web-secure
      service: kumbio-booking
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    catchAllRouter:
      rule: "PathPrefix(`/`)"
      entrypoints:
        - web-secure
      middlewares:
        - catchAll
      service: kumbio-booking
      priority: 1
      tls:
        certResolver: letsencrypt
        domains:
          - main: "testing.agenda.kumbio.com"
          - sans: "*.kumbio.com"
  
  middlewares:
    catchAll:
      redirectregex:
        regex: "^.*$"
        replacement: "https://agenda.kumbio.com/${1}"
        permanent: false

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    kumbio-app:
      loadBalancer:
        servers:
          - url: http://kumbio-app:3000

    kumbio-booking:
      loadBalancer:
        servers:
          - url: http://kumbio-booking:3000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
